name: panda_sync
description: >
  Seamless offline-first client library designed for easy under the hood management of lost 
  connection. Inspired by Dio and Flutter_Data.
version: 1.0.0
homepage: https://github.com/red-panda-solutions/panda-sync
documentation: https://github.com/red-panda-solutions/panda-sync

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1


# Exclude specific directories from publishing
files:
  exclude:
    - example/pandasyncServerTodo
    - example/panda_sync_todo